services:
  webserver:
    image: nginx:1.27.4
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "8008:8008"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./domain.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - /etc/letsencrypt/live/mehrad-test.ir/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/nginx/ssl/privkey.pem
      - ./.htpasswd:/etc/nginx/.htpasswd