services:
  webserver:
    image: nginx:1.27.4
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "8008:8008"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./certs/localhost.crt:/etc/nginx/ssl/localhost.crt
      - ./certs/localhost.key:/etc/nginx/ssl/localhost.key
      - ./.htpasswd:/etc/nginx/.htpasswd